### ISSUE TITLE
Support for recursive poly struct?

### ISSUE THREAD

**Issue by fengye87** [polyfloyd/gopolyjson#18]
I bumped into this project while looking for a lib to solve marshaling my poly struct to JSON (and back from it too). But my poly struct is recursive. Say like

```go
type Shape interface {}

type Square struct {
    ...
    Child Shape
}

type Triangle struct {
    ...
    Child Shape
}
```

So `Child` would not marshal/unmarshal as expected here. Any way to support it?

**Comment by polyfloyd** [comment]
Hmmm, I thought I had already implemented support for something like this. I'll double check

**Comment by fengye87** [comment]
Sorry, my bad. It's already handled well. Closing this issue.
